import { useEffect, useState } from 'react';
import { useT, type Translate } from './i18n';
import { getJson, range, type Backlog, type BacklogItem } from './workspace';

/**
 * Turns the acceptance criteria into lines a screen can show.
 *
 * The criteria are HTML on purpose: they are written for the Azure DevOps field that expects
 * HTML, and changing that to please this page would change what gets published. So the page
 * reads the markup rather than the product producing two versions of the same sentence.
 *
 * Parsed rather than injected. It is generated by our own backlog builder and would almost
 * certainly be safe, but "almost certainly safe" plus dangerouslySetInnerHTML is how a
 * component name in a client's estate ends up executing on this page. Only the shape the
 * builder emits is understood: paragraphs, line breaks and a bold lead-in per line.
 */
function criteriaLines(html: string): { label: string | null; text: string }[] {
  if (!html) return [];

  return html
    // Paragraph and line breaks are where one clause ends and the next begins.
    .replace(/<\/p>|<br\s*\/?>/gi, '\n')
    .split('\n')
    .map((line) => {
      // A bold lead-in is the Given, the When, the Then or the Test. Kept as a label so the
      // page can set it apart the way the markup meant it to be.
      const lead = /^\s*<p>?\s*<b>(.*?)<\/b>\s*/i.exec(line);
      const label = lead ? strip(lead[1]) : null;
      const text = strip(lead ? line.slice(lead[0].length) : line);

      return { label, text };
    })
    .filter((line) => line.label !== null || line.text !== '');
}

/** Everything that is not text, removed, and the handful of entities that survive it decoded. */
function strip(value: string): string {
  return value
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .trim();
}

/** The criteria and the test, rendered as the clauses they are. */
function Criteria({ item, t }: { item: BacklogItem; t: Translate }) {
  const lines = criteriaLines(item.acceptanceCriteria);

  return (
    <div className="criteria">
      <p className="eyebrow">{t('backlog.acceptance')}</p>

      {lines.length === 0
        ? <p className="hint">{t('backlog.no-criteria')}</p>
        : (
          <dl className="criteria-list">
            {lines.map((line, index) => (
              <div key={index}>
                {line.label !== null && <dt>{line.label}</dt>}
                <dd>{line.text}</dd>
              </div>
            ))}
          </dl>
        )}

      {item.testRequirement && (
        <>
          <p className="eyebrow">{t('backlog.test')}</p>
          <p className="criteria-test">{strip(item.testRequirement)}</p>
        </>
      )}
    </div>
  );
}

/**
 * One item and everything under it.
 *
 * A details element rather than state of its own. The backlog is a tree three deep and a
 * few hundred wide, and holding an open-or-closed flag per node in React state is a lot of
 * machinery for something the browser already does, keeps accessible, and makes findable
 * with the browser's own page search.
 *
 * Closed by default below the top level. The point of the tree is that somebody can read
 * the shape of the work before reading any of it.
 */
function Item({ item, childrenOf, t, depth }: {
  item: BacklogItem;
  childrenOf: Map<string, BacklogItem[]>;
  t: Translate;
  depth: number;
}) {
  const children = childrenOf.get(item.backlogItemId) ?? [];
  const hours = range(item.lowHours, item.highHours);

  return (
    <details className={`backlog-item depth-${depth}`} open={depth === 0}>
      <summary>
        <span className="backlog-title">
          <span className={`tag type-${item.workItemType}`}>{t('backlog.type-' + item.workItemType)}</span>
          <strong>{item.title}</strong>
        </span>

        <span className="backlog-numbers">
          {children.length > 0 && (
            <span className="hint">{t('backlog.n-items', children.length)}</span>
          )}
          {item.storyPoints !== null && <span className="tag muted">{item.storyPoints}</span>}
          <span className="backlog-hours">{hours}</span>
        </span>
      </summary>

      <div className="backlog-body">
        <Criteria item={item} t={t} />

        {children.length > 0 && (
          <div className="backlog-children">
            {children
              .slice()
              .sort((a, b) => a.priority - b.priority)
              .map((child) => (
                <Item key={child.backlogItemId} item={child} childrenOf={childrenOf} t={t} depth={depth + 1} />
              ))}
          </div>
        )}
      </div>
    </details>
  );
}

/**
 * The work items, before anybody publishes anything.
 *
 * Deliberately a first class screen rather than an appendix. Naming every component that
 * needs work, with what "done" means for it, is useful; saying "there is technical debt" is
 * not, and the difference is what a client is actually buying when they ask what it costs.
 *
 * Shown as the tree the builder produced rather than as a table per work item type. The
 * builder groups deliberately: an epic per category, a feature per rule that needs one, a
 * story per finding worth naming, and the trivia batched. Flattening that into four tables
 * threw the grouping away and left a reader scrolling through three hundred rows of
 * acceptance criteria looking for the shape of the work.
 *
 * Nothing on this screen has been published. Publishing is a separate act behind an approval
 * bound to the exact backlog somebody read, which is why this page shows the backlog and
 * offers no button that writes anywhere.
 */
export function BacklogPage({ engagementId }: { engagementId: string }) {
  const t = useT();
  const [backlog, setBacklog] = useState<Backlog | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    void getJson<Backlog>(`/api/engagements/${engagementId}/backlog`).then((result) => {
      if (cancelled) return;
      if (result.data) setBacklog(result.data);
      else setError(result.error);
    });

    return () => { cancelled = true; };
  }, [engagementId]);

  if (error) return <p className="error">{error}</p>;

  if (!backlog) {
    return <section className="panel"><p className="dashboard-empty">{t('common.loading')}</p></section>;
  }

  if (backlog.items.length === 0) {
    return (
      <section className="panel">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">{t('view.backlog')}</p>
            <h2>{t('backlog.nothing-in-the-backlog')}</h2>
          </div>
        </div>
        <p className="panel-note">{t('page.backlog')}</p>
      </section>
    );
  }

  const childrenOf = new Map<string, BacklogItem[]>();

  for (const item of backlog.items) {
    if (item.parentItemId === null) continue;
    const siblings = childrenOf.get(item.parentItemId);

    if (siblings === undefined) childrenOf.set(item.parentItemId, [item]);
    else siblings.push(item);
  }

  // A parent that is not in the list would take its children with it, so anything whose
  // parent is missing is treated as a root rather than silently dropped.
  const known = new Set(backlog.items.map((item) => item.backlogItemId));

  const roots = backlog.items
    .filter((item) => item.parentItemId === null || !known.has(item.parentItemId))
    .sort((a, b) => a.priority - b.priority);

  const totalLow = backlog.items.reduce((sum, item) => sum + (item.parentItemId === null ? item.lowHours : 0), 0);
  const totalHigh = backlog.items.reduce((sum, item) => sum + (item.parentItemId === null ? item.highHours : 0), 0);

  return (
    <section className="panel">
      <div className="panel-heading">
        <div>
          <p className="eyebrow">{t('view.backlog')}</p>
          <h2>{t('backlog.n-items', backlog.items.length)}</h2>
        </div>
        <span className="tag muted">{range(totalLow, totalHigh)}</span>
      </div>

      <div className="backlog-tree">
        {roots.map((item) => (
          <Item key={item.backlogItemId} item={item} childrenOf={childrenOf} t={t} depth={0} />
        ))}
      </div>

      <p className="panel-note">{t('backlog.nothing-published-yet')}</p>
    </section>
  );
}
