import { useEffect, useState } from 'react';
import { useT, type Translate } from './i18n';
import { getJson, sendJson, range, type Backlog, type BacklogItem, type Connection } from './workspace';
import { useCan } from './access';

/**
 * Turns the acceptance criteria into lines a screen can show.
 *
 * The criteria are HTML on purpose: they are written for the Azure DevOps field that expects
 * HTML, and changing that to please this page would change what gets published. So the page
 * reads the markup rather than the product producing two versions of the same sentence.
 *
 * Parsed rather than injected. It is generated by our own backlog builder and would almost
 * certainly be safe, but "almost certainly safe" plus dangerouslySetInnerHTML is how a
 * component name in a client's estate ends up executing on this page. Only the shape the
 * builder emits is understood: paragraphs, line breaks and a bold lead-in per line.
 */
function criteriaLines(html: string): { label: string | null; text: string }[] {
  if (!html) return [];

  return html
    // Paragraph and line breaks are where one clause ends and the next begins.
    .replace(/<\/p>|<br\s*\/?>/gi, '\n')
    .split('\n')
    .map((line) => {
      // A bold lead-in is the Given, the When, the Then or the Test. Kept as a label so the
      // page can set it apart the way the markup meant it to be.
      const lead = /^\s*<p>?\s*<b>(.*?)<\/b>\s*/i.exec(line);
      const label = lead ? strip(lead[1]) : null;
      const text = strip(lead ? line.slice(lead[0].length) : line);

      return { label, text };
    })
    .filter((line) => line.label !== null || line.text !== '');
}

/** Everything that is not text, removed, and the handful of entities that survive it decoded. */
function strip(value: string): string {
  return value
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .trim();
}

/** The criteria and the test, rendered as the clauses they are. */
function Criteria({ item, t }: { item: BacklogItem; t: Translate }) {
  const lines = criteriaLines(item.acceptanceCriteria);

  return (
    <div className="criteria">
      <p className="eyebrow">{t('backlog.acceptance')}</p>

      {lines.length === 0
        ? <p className="hint">{t('backlog.no-criteria')}</p>
        : (
          <dl className="criteria-list">
            {lines.map((line, index) => (
              <div key={index}>
                {line.label !== null && <dt>{line.label}</dt>}
                <dd>{line.text}</dd>
              </div>
            ))}
          </dl>
        )}

      {item.testRequirement && (
        <>
          <p className="eyebrow">{t('backlog.test')}</p>
          <p className="criteria-test">{strip(item.testRequirement)}</p>
        </>
      )}
    </div>
  );
}

/**
 * One item and everything under it.
 *
 * A details element rather than state of its own. The backlog is a tree three deep and a
 * few hundred wide, and holding an open-or-closed flag per node in React state is a lot of
 * machinery for something the browser already does, keeps accessible, and makes findable
 * with the browser's own page search.
 *
 * Closed by default below the top level. The point of the tree is that somebody can read
 * the shape of the work before reading any of it.
 */
function Item({ item, childrenOf, t, depth, selected, onToggle }: {
  item: BacklogItem;
  childrenOf: Map<string, BacklogItem[]>;
  t: Translate;
  depth: number;

  /** The keys ticked, or null where nothing is choosing anything. */
  selected: Set<string> | null;
  onToggle: (item: BacklogItem, on: boolean) => void;
}) {
  const children = childrenOf.get(item.backlogItemId) ?? [];
  const hours = range(item.lowHours, item.highHours);
  const ticked = selected?.has(item.deterministicKey) ?? false;

  return (
    <details className={`backlog-item depth-${depth}`} open={depth === 0}>
      <summary>
        <span className="backlog-title">
          {selected !== null && (
            /* Stops the click reaching the summary, which would toggle the fold rather
               than the box and makes ticking a parent feel like it did nothing. */
            <input
              type="checkbox"
              className="backlog-tick"
              checked={ticked}
              aria-label={item.title}
              onClick={(event) => event.stopPropagation()}
              onChange={(event) => onToggle(item, event.target.checked)}
            />
          )}
          <span className={`tag type-${item.workItemType}`}>{t('backlog.type-' + item.workItemType)}</span>
          <strong>{item.title}</strong>
        </span>

        <span className="backlog-numbers">
          {children.length > 0 && (
            <span className="hint">{t('backlog.n-items', children.length)}</span>
          )}
          {item.storyPoints !== null && <span className="tag muted">{item.storyPoints}</span>}
          <span className="backlog-hours">{hours}</span>
        </span>
      </summary>

      <div className="backlog-body">
        <Criteria item={item} t={t} />

        {children.length > 0 && (
          <div className="backlog-children">
            {children
              .slice()
              .sort((a, b) => a.priority - b.priority)
              .map((child) => (
                <Item
              key={child.backlogItemId}
              item={child}
              childrenOf={childrenOf}
              t={t}
              depth={depth + 1}
              selected={selected}
              onToggle={onToggle}
            />
              ))}
          </div>
        )}
      </div>
    </details>
  );
}

/**
 * The work items, before anybody publishes anything.
 *
 * Deliberately a first class screen rather than an appendix. Naming every component that
 * needs work, with what "done" means for it, is useful; saying "there is technical debt" is
 * not, and the difference is what a client is actually buying when they ask what it costs.
 *
 * Shown as the tree the builder produced rather than as a table per work item type. The
 * builder groups deliberately: an epic per category, a feature per rule that needs one, a
 * story per finding worth naming, and the trivia batched. Flattening that into four tables
 * threw the grouping away and left a reader scrolling through three hundred rows of
 * acceptance criteria looking for the shape of the work.
 *
 * Nothing on this screen has been published. Publishing is a separate act behind an approval
 * bound to the exact backlog somebody read, which is why this page shows the backlog and
 * offers no button that writes anywhere.
 */
export function BacklogPage({ engagementId }: { engagementId: string }) {
  const t = useT();
  const canPublish = useCan('Contributor');
  const [backlog, setBacklog] = useState<Backlog | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  /**
   * Ticks an item and everything under it.
   *
   * Ticking an epic means the epic and its children, because nobody ticking "ALM" means
   * the empty container. Unticking does the same in reverse. The parents of a ticked child
   * are added by the server rather than here: a child published without its parent is an
   * orphan in the target project, and that rule belongs where it cannot be skipped.
   */
  function toggle(item: BacklogItem, on: boolean) {
    setSelected((current) => {
      const next = new Set(current);
      const items = backlog?.items ?? [];

      const subtree = (id: string): BacklogItem[] => {
        const mine = items.filter((candidate) => candidate.parentItemId === id);
        return [...mine, ...mine.flatMap((child) => subtree(child.backlogItemId))];
      };

      for (const affected of [item, ...subtree(item.backlogItemId)]) {
        if (on) next.add(affected.deterministicKey);
        else next.delete(affected.deterministicKey);
      }

      return next;
    });
  }

  useEffect(() => {
    let cancelled = false;

    void getJson<Backlog>(`/api/engagements/${engagementId}/backlog`).then((result) => {
      if (cancelled) return;
      if (result.data) setBacklog(result.data);
      else setError(result.error);
    });

    return () => { cancelled = true; };
  }, [engagementId]);

  if (error) return <p className="error">{error}</p>;

  if (!backlog) {
    return <section className="panel"><p className="dashboard-empty">{t('common.loading')}</p></section>;
  }

  if (backlog.items.length === 0) {
    return (
      <section className="panel">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">{t('view.backlog')}</p>
            <h2>{t('backlog.nothing-in-the-backlog')}</h2>
          </div>
        </div>
        <p className="panel-note">{t('page.backlog')}</p>
      </section>
    );
  }

  const childrenOf = new Map<string, BacklogItem[]>();

  for (const item of backlog.items) {
    if (item.parentItemId === null) continue;
    const siblings = childrenOf.get(item.parentItemId);

    if (siblings === undefined) childrenOf.set(item.parentItemId, [item]);
    else siblings.push(item);
  }

  // A parent that is not in the list would take its children with it, so anything whose
  // parent is missing is treated as a root rather than silently dropped.
  const known = new Set(backlog.items.map((item) => item.backlogItemId));

  const roots = backlog.items
    .filter((item) => item.parentItemId === null || !known.has(item.parentItemId))
    .sort((a, b) => a.priority - b.priority);

  const totalLow = backlog.items.reduce((sum, item) => sum + (item.parentItemId === null ? item.lowHours : 0), 0);
  const totalHigh = backlog.items.reduce((sum, item) => sum + (item.parentItemId === null ? item.highHours : 0), 0);

  return (
    <section className="panel">
      <div className="panel-heading">
        <div>
          <p className="eyebrow">{t('view.backlog')}</p>
          <h2>{t('backlog.n-items', backlog.items.length)}</h2>
        </div>
        <span className="tag muted">{range(totalLow, totalHigh)}</span>
      </div>

      <div className="backlog-tree">
        {roots.map((item) => (
          <Item
            key={item.backlogItemId}
            item={item}
            childrenOf={childrenOf}
            t={t}
            depth={0}
            selected={canPublish ? selected : null}
            onToggle={toggle}
          />
        ))}
      </div>

      {canPublish && (
        <PublishPanel
          engagementId={engagementId}
          selected={selected}
          total={backlog.items.length}
          onClear={() => setSelected(new Set())}
          t={t}
        />
      )}

      <p className="panel-note">{t('backlog.nothing-published-yet')}</p>
    </section>
  );
}

/** One project in an Azure DevOps organisation. */
type Project = { id: string; name: string; description: string | null };

/**
 * Where a chosen part of the backlog goes.
 *
 * The project is a list rather than a text box, loaded through the same token that will do
 * the publishing. Azure DevOps answers 404 both for a project that does not exist and for
 * one the token cannot see, so a typed name fails in the one way nobody can diagnose.
 *
 * Nothing is published until somebody has seen a count. A dry run is offered first and is
 * the default thing to press, because the mistake this screen can make is putting several
 * hundred work items into a client's project, and that mistake is not undoable from here.
 */
function PublishPanel({ engagementId, selected, total, onClear, t }: {
  engagementId: string;
  selected: Set<string>;
  total: number;
  onClear: () => void;
  t: Translate;
}) {
  const [targets, setTargets] = useState<Connection[]>([]);
  const [connectionId, setConnectionId] = useState('');
  const [projects, setProjects] = useState<Project[]>([]);
  const [project, setProject] = useState('');
  const [loadingProjects, setLoadingProjects] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    void getJson<Connection[]>(`/api/engagements/${engagementId}/connections`).then((answer) => {
      if (cancelled) return;

      const found = (answer.data ?? []).filter((candidate) => candidate.mode === 'azureDevOps');
      setTargets(found);
      if (found.length === 1) setConnectionId(found[0].connectionId);
    });

    return () => { cancelled = true; };
  }, [engagementId]);

  // The projects come from the organisation the chosen connection points at, so they are
  // reloaded whenever that changes rather than once on mount.
  useEffect(() => {
    if (!connectionId) { setProjects([]); return; }

    let cancelled = false;
    setLoadingProjects(true);
    setError(null);

    void getJson<Project[]>(`/api/engagements/${engagementId}/connections/${connectionId}/projects`)
      .then((answer) => {
        if (cancelled) return;

        setProjects(answer.data ?? []);
        setProject(answer.data?.length === 1 ? answer.data[0].name : '');
        setError(answer.error);
        setLoadingProjects(false);
      });

    return () => { cancelled = true; };
  }, [engagementId, connectionId]);

  async function publish(dryRun: boolean) {
    setBusy(true);
    setError(null);
    setResult(null);

    const answer = await sendJson<{
      published: number; requested: number; parentsIncluded: number; dryRun: boolean;
    }>(`/api/engagements/${engagementId}/publish`, 'POST', {
      connectionId,
      project,
      keys: [...selected],
      dryRun
    });

    setBusy(false);

    if (answer.error) { setError(answer.error); return; }
    if (!answer.data) return;

    const { published, parentsIncluded } = answer.data;

    setResult(dryRun
      ? t('backlog.publish.would', published)
      : t('backlog.publish.done', published));

    // Said because it is surprising: ticking a task pulls in the epic above it, and a
    // count larger than the boxes ticked needs a reason before somebody thinks it
    // published the wrong thing.
    if (parentsIncluded > 0) {
      setResult((current) => `${current} ${t('backlog.publish.parents', parentsIncluded)}`);
    }
  }

  if (targets.length === 0) {
    return (
      <div className="publish-panel">
        <h3>{t('backlog.publish')}</h3>
        <p className="muted">{t('backlog.publish.no-target')}</p>
      </div>
    );
  }

  const count = selected.size;
  const ready = connectionId !== '' && project !== '' && count > 0 && !busy;

  return (
    <div className="publish-panel">
      <h3>{t('backlog.publish')}</h3>

      <div className="field-row">
        <label>
          {t('backlog.publish.target')}
          <select value={connectionId} onChange={(event) => setConnectionId(event.target.value)}>
            <option value="">{t('backlog.publish.choose-target')}</option>
            {targets.map((target) => (
              <option key={target.connectionId} value={target.connectionId}>{target.name}</option>
            ))}
          </select>
        </label>

        <label>
          {t('backlog.publish.project')}
          <select
            value={project}
            disabled={loadingProjects || projects.length === 0}
            onChange={(event) => setProject(event.target.value)}>
            <option value="">
              {loadingProjects ? t('common.loading') : t('backlog.publish.choose-project')}
            </option>
            {projects.map((candidate) => (
              <option key={candidate.id} value={candidate.name}>{candidate.name}</option>
            ))}
          </select>
        </label>
      </div>

      <p className="muted">
        {count === 0 ? t('backlog.publish.nothing-selected', total) : t('backlog.publish.n-selected', count)}
        {count > 0 && <> · <button type="button" className="link-button" onClick={onClear}>{t('common.clear')}</button></>}
      </p>

      <div className="field-row">
        <button type="button" className="secondary-button" disabled={!ready} onClick={() => void publish(true)}>
          {t('backlog.publish.dry-run')}
        </button>
        <button type="button" className="primary-button" disabled={!ready} onClick={() => void publish(false)}>
          {t('backlog.publish.go', count)}
        </button>
      </div>

      {error && <p className="error">{error}</p>}
      {result && <p className="curation-message">{result}</p>}
    </div>
  );
}
